# Generated by Django 5.2.7 on 2025-10-05 03:38

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.CharField(blank=True, default='Описание отсутствует', max_length=2048, null=True)),
                ('request_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('PRINTER', 'Принтер'), ('SOFTWARE', 'Программа'), ('HARDWARE', 'Компьютер'), ('ETC', 'Другое')])),
                ('status', models.CharField(choices=[('WORKING', 'В работе'), ('COMPLETED', 'Выполнено'), ('REJECTED', 'Отклонено')])),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('docx', 'Word'), ('xlsx', 'Excel'), ('pdf', 'PDF'), ('png', 'Картинка')])),
                ('file', models.FileField(upload_to=main.models.upload_path)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.request')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('curator', 'Куратор'), ('worker', 'Сотрудник')])),
                ('full_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.worker'),
        ),
    ]
