# Generated by Django 5.2.7 on 2025-10-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('WORKING', 'В работе'), ('COMPLETED', 'Выполнено'), ('REJECTED', 'Отклонено')], default='WORKING'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('worker', 'Сотрудник')]),
        ),
    ]
