# Generated by Django 5.2.7 on 2025-10-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_request_status_alter_worker_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='_from',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('worker', 'Сотрудник')], default='worker'),
        ),
    ]
