# Generated by Django 5.2.7 on 2025-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename__from_request_sender_alter_worker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='place',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
